[project]
name = "groq-exemplo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "groq>=1.0.0",
    "openai>=2.14.0",
]
