[project]
name = "example-vector-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "groq>=1.0.0",
    "numpy>=2.4.0",
    "qdrant-client>=1.16.2",
    "sentence-transformers>=5.2.0",
]
